GrapePhoto/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GrapePhoto.Extensions;
using GrapePhoto.Proxy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Amazon.S3;
using GrapePhoto.Web.Models;
using GrapePhoto.Models;
using GrapePhoto.Helper;
using GrapePhoto.Web.Models.Posts;
using Newtonsoft.Json;

namespace GrapePhoto.Controllers
{
    public class CommonController : Controller
    {
        private IPictureService _pictureService;
        private IPostService _postService;
        private IAccountClient _accountClient;

        public CommonController(IPictureService pictureService, IPostService postService, IAccountClient accountClient)
        {
            _pictureService = pictureService;
            _postService = postService;
            _accountClient = accountClient;
        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<string> AsyncUpload(string comments)
        {
            var pictureComments = comments != null ? comments.Trim() : "";
            if (string.IsNullOrEmpty(pictureComments))
            {
                return JsonConvert.SerializeObject(new
                {
                    success = false,
                    message = "please enter your comments",
                });
            }
            var httpPostedFile = Request.Form.Files.FirstOrDefault();
                if (httpPostedFile == null)
                {
                    return JsonConvert.SerializeObject(new
                    {
                        success = false,
                        message = "No file uploaded",
                    });
                }

                var qqFileNameParameter = "qqfile";
                var fileName = httpPostedFile.FileName;
                if (string.IsNullOrEmpty(fileName) && Request.Form.ContainsKey(qqFileNameParameter))
                    fileName = Request.Form[qqFileNameParameter].ToString();
                //remove path (passed in IE)
                fileName = Path.GetFileName(fileName);
                var contentType = httpPostedFile.ContentType;
                var fileExtension = Path.GetExtension(fileName);
                if (!string.IsNullOrEmpty(fileExtension))
                    fileExtension = fileExtension.ToLowerInvariant();

                var provider = new FileExtensionContentTypeProvider();
                if (string.IsNullOrEmpty(contentType))
                {
                    contentType = provider.Mappings[fileExtension];
                }


                var id = Guid.NewGuid().ToString();
                string s3FileName = $"{id}{fileExtension}";

                var bytes = httpPostedFile.GetDownloadBits();

                var picture = new Picture()
                {
                    Id = id,
                    S3FileName = s3FileName,
                    Bytes = bytes,
                    MimeType = contentType
                };

                _pictureService.InsertPicture(picture);
                if (string.IsNullOrEmpty(comments))
                {
                    comments = " ";
                }
                var post = new PostDto()
                {
                    Title = comments,
                    ImgUrl = picture.Src,
                    ThumbUrl = picture.ThumbnailSrc,
                    UserId = HttpContext.User.Identity.Name,
                    Width = picture.Width,
                    Height = picture.Height
                };

                _postService.AddPost(post);


            var result = _accountClient.GetAllFollowersUsersByUserId(HttpContext.User.Identity.Name.ToString());
            var followerList = result.Select(o => o.UserId).ToList();


            var m = new Message()
            {
                UserName = HttpContext.User.Identity.Name.ToString(),
                Content = comments,
                ImageUrl = picture.Src,
                Followers = followerList
            };

            if(followerList.Count>=1)
            await Channel.Trigger(m, "feed", "new_feed");



            return JsonConvert.SerializeObject(new
            {
                success = true,
                message = "uploaded",
            });
        }

        



        [HttpPost]
        public JsonResult Follow(string id)
        {

            _accountClient.FollowOtherUser(HttpContext.User.Identity.Name, id);
            return Json(new {
                success = true
            });
        }

        [HttpPost]
        public JsonResult Unfollow(string id)
        {
            _accountClient.UnfollowOtherUser(HttpContext.User.Identity.Name, id);
            return Json(new
            {
                success = true
            });
        }

        [HttpPost]
        public JsonResult LikePost(string postId)
        {
            var post = new LikePostDto() { PostId = postId, UserId = HttpContext.User.Identity.Name, IsLike = true };
            var result = _postService.LikePost(post);
            return Json(new
            {
                success = true,
                count = result.LikeCount
            });
        }
        [HttpPost]
        public JsonResult DislikePost(string postId)
        {
            var post = new LikePostDto() { PostId = postId, UserId = HttpContext.User.Identity.Name, IsLike = false };
            var result = _postService.LikePost(post);
            return Json(new
            {
                success = true,
                count = result.LikeCount
            });
        }
    }
}

GrapePhoto/Controllers/HomeController.cs
namespace GrapePhoto.Controllers
{
    using GrapePhoto.Helper;
    using GrapePhoto.Models;
    using GrapePhoto.Models.Consts;
    using GrapePhoto.Proxy;
    using GrapePhoto.Web.Models;
    using GrapePhoto.Web.Models.Account;
    using GrapePhoto.Web.Models.Posts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;
    using System.Linq;

    [Authorize]
    public class HomeController : Controller
    {
        private IPictureService _pictureService;
        private IPostService _postService;
        private IAccountClient _accountService;

        public HomeController(IPictureService pictureService, IAccountClient client, IPostService postService)
        {
            this._pictureService = pictureService;
            this._accountService = client;
            this._postService = postService;
        }

        public IActionResult Error()
        {
            ErrorViewModel model = new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? base.HttpContext.TraceIdentifier
            };
            return this.View(model);
        }

        public IActionResult Explore()
        {
            List<PostViewModel> allPictures = this.GetAllPictures(0);
            IndexViewModel model = new IndexViewModel
            {
                Posts = allPictures
            };
            return this.View(model);
        }
   
        [HttpPost]
        public JsonResult GetExploreJson(int pageIndex) =>
            this.Json(this.GetAllPictures(pageIndex));


        public IActionResult Index()
        {
            IndexViewModel model = new IndexViewModel
            {
                Posts = this.GetRecentFollowingPosts(0),
                FollowingUsers = this._accountService.GetAllFollowingUsersByUserId(base.HttpContext.User.Identity.Name)
            };
            return this.View(model);
        }

        [HttpPost]
        public JsonResult GetPosts(int pageIndex)
        {
            List<PostViewModel> recentFollowingPosts = this.GetRecentFollowingPosts(pageIndex);
            return this.Json(recentFollowingPosts);
        }
      

        #region Prepare ViewModel
        private List<PostViewModel> GetAllPictures(int pageIndex)
        {
            List<PostViewModel> list = new List<PostViewModel>();
            var userid = HttpContext.User.Identity.Name;
            var posts = this._postService.GetPosts(userid, pageIndex, PaginationConsts.PageSize);
            PreparePostViewModel(list, posts);
            return list;
        }
        private List<PostViewModel> GetRecentFollowingPosts(int page)
        {
            string userid = this.HttpContext.User.Identity.Name;
            List<PostViewModel> list = new List<PostViewModel>();
            var followingPosts = this._postService.GetFollowingPostsByUserId(userid, page, PaginationConsts.PageSize);
            PreparePostViewModel(list, followingPosts);
            return list;
        }
        private void PreparePostViewModel(List<PostViewModel> list, IPagedList<PostDto> posts)
        {
            foreach (var post in posts)
            {
                PostViewModel model1 = new PostViewModel
                {
                    Picture = new Picture()
                    {
                        Src = post.ImgUrl,
                        ThumbnailSrc = post.ThumbUrl,
                        TitleAttribute = post.Title,
                        PostDate = post.PostDate,
                        LikeCount = post.LikeCount,
                        Width = post.Width,
                        Height = post.Height,
                        Id = post.Id,
                        UserId = post.UserId,
                        AltAttribute = post.Title
                    },
                    User = this._accountService.GetUserByUserId(post.UserId),
                    IsLike = post.Liked == 1
                };
                list.Add(model1);
            }
        }

    
        #endregion 
    }
}

GrapePhoto/Controllers/ProfileController.cs
using GrapePhoto.Models;
using GrapePhoto.Proxy;
using GrapePhoto.Web.Models.Account;
using Microsoft.AspNetCore.Mvc;

namespace GrapePhoto.Controllers
{
    public class ProfileController : Controller
    {
        private IAccountClient _accountClient;
        private IPostService _postService;

        public ProfileController(IAccountClient accountClient, IPostService postService)
        {
            _accountClient = accountClient;
            _postService = postService;
        }
        public IActionResult Index(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                id = HttpContext.User.Identity.Name;
            }
            var indexModel = new ProfileIndexModel(_accountClient);
            indexModel.User = _accountClient.GetUserByUserId(id);
            indexModel.Posts = _postService.GetUserPostsByUserId(id);
            indexModel.SetRelationship(HttpContext.User.Identity.Name);
            return View(indexModel);
        }


        public IActionResult Edit()
        {
            var user = new User();
            user = _accountClient.GetUserByUserId(HttpContext.User.Identity.Name);
            return View(user);
        }


        [HttpPost]
        public IActionResult Edit(GrapePhoto.Web.Models.Account.User model)
        {
            if (ModelState.IsValid)
            {
                var UserId = HttpContext.User.Identity.Name;
                var user = _accountClient.GetUserByUserId(UserId);
                user.Email = model.Email;
                user.UserName = model.UserName;
                _accountClient.UpdateProfile(user);
                ViewBag.Message = "Save profile successful";
            }
            return View(model);
        }

        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModels model)
        {
            if (ModelState.IsValid)
            {
                var result =  _accountClient.SignIn(new SignInViewModel()
                {
                    UserId = HttpContext.User.Identity.Name,
                    Password = model.OldPassword
                });

                if (result.Succeed)
                {
                    User user = new User
                    {
                        UserId = HttpContext.User.Identity.Name,
                        Password = model.NewPassword
                    };
                    _accountClient.UpdateProfile(user);

                    ViewBag.Message = "Change password successful";
                }
                ModelState.AddModelError(string.Empty, result.ErrorMessage);
            }
            return View(model);
        }
    }
}

GrapePhoto/Views/Home/Explore.cshtml
@model IndexViewModel

<div class="row row-cards">
    @foreach (var item in Model.Posts)
    {
        @Html.Partial("UserPhotosThreeColumnsTemplate", item)
    }
</div>

@section Scripts{
    <script>
        require(['jquery'], function () {
            $(document).ready(function () {
                $("#explorelink").addClass("active");
            });
        });


        require(['jquery', '../lib/photoswipe/dist/photoswipe.js', '../lib/photoswipe/dist/photoswipe-ui-default.js'],
            function ($, PhotoSwipe, PhotoSwipeUI_Default) {
                $(document).ready(function () {
                    $("img.grapephoto").click(function (e) {
                        var index = $('img.grapephoto').index(this);

                        var pswpElement = document.querySelectorAll('.pswp')[0];
                        var items = [];
                        $("img.grapephoto").each(function (index, value) {
                            var imageLink = $(value).closest("a").attr("src");
                            var w = $(this).parent("a").data("width");
                            var h = $(this).parent("a").data("height");

                            items.push({
                                src: imageLink,
                                w: w,
                                h: h
                            });
                        });
                        var options = {
                            index: index,
                            history: false,
                            focus: false,
                            showAnimationDuration: 0,
                            hideAnimationDuration: 0
                        };

                        var gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, items, options);
                        gallery.init();
                    });

                });
            });
    </script>
}

GrapePhoto/Views/Home/Index.cshtml
@model IndexViewModel
@using GrapePhoto.Views.Shared.ViewComponents

@if (Model.FollowingUsers.Any())
{
    <div class="row">
        <div class="col-lg-8">
            @foreach (var item in Model.Posts)
            {
                @Html.Partial("_FollowingPost", item)
            }
        </div>
        <div class="col-lg-4 parent-container" id="index-right">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Following</h3>
                </div>
                <div class="card-body o-auto" style="height: 30rem">
                    <ul class="list-unstyled list-separated">
                        @foreach (var user in Model.FollowingUsers)
                        {
                            @Html.Partial("_FollowingUserItems", user)
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
}
else
{
    @await Component.InvokeAsync(typeof(PopularUserComponent), new { numberOfItems = 11 })
}

@Html.Partial("_FloatingButton")
@Html.Partial("_AddPostDialog")

@section Scripts{
    <script>

        require(['jquery','../lib/sweetalert2/dist/sweetalert2.all.min.js'], function ($, Swal) {
            $(document).ready(function () {
                $("#homelink").addClass("active");


                $('.btn-post').click(function () {
                    console.log("adding post.");
                    var url = '@Url.Action("AsyncUpload","Common")';
                    var formData = new FormData($("#addPostForm")[0]);
                    $("#addpostcontent").addClass("active");
                    $.ajax({
                        method: 'post',
                        url: url,
                        data: formData,
                        dataType: "json",
                        processData: false,
                        contentType: false,
                        success: function (data) {
                            $("#addpostcontent").removeClass("active");
                            if (data.success) {

                                location.reload();
                            }
                            else {
                                Swal('Oops...', data.message, 'error')

                            }
                        }, //End of AJAX Success function

                        failure: function (data) {
                            console.log(data);
                        }, //End of AJAX failure function
                        error: function (data) {
                            console.log(data);
                        } //End of AJAX error function
                    });
                });

                bindingUnfollowEvent();
            });
            function bindingUnfollowEvent() {

                    $('.unfollowaction').click(function () {
                    var url = '@Url.Action("Unfollow","Common")';

                    var self = this;
                    var followUserId = $(this).data("id");

                    $.ajax({
                        method: 'post',
                        url: url,
                        data: { id: followUserId },
                        dataType: "json",
                        success: function (data) {

                            console.log(data);
                            if (data.success) {
                                location.reload();
                            }
                            else {
                                Swal('Oops...', data.message, 'error')
                            }
                        }, //End of AJAX Success function

                        failure: function (data) {
                            console.log(data);
                        }, //End of AJAX failure function
                        error: function (data) {
                            console.log(data);
                        } //End of AJAX error function
                    });
                });

              }
        });

        require(['jquery', '../lib/photoswipe/dist/photoswipe.js', '../lib/photoswipe/dist/photoswipe-ui-default.js'],
            function ($, PhotoSwipe, PhotoSwipeUI_Default) {
                $(document).ready(function () {
                    $("img.grapephoto").click(function (e) {
                        var index = $('img.grapephoto').index(this);
                        console.log(index);
                        var pswpElement = document.querySelectorAll('.pswp')[0];
                        var items = [];
                        $("img.grapephoto").each(function (index, value) {
                            var imageLink = $(value).closest("a").attr("src");
                            var w = $(value).closest("a").data("width");
                            var h = $(value).closest("a").data("height");
                            items.push({
                                src: imageLink,
                                w: w,
                                h: h
                            });
                        });
                        var options = {
                            index: index,
                            history: false,
                            focus: false,
                            showAnimationDuration: 0,
                            hideAnimationDuration: 0
                        };

                        var gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, items, options);
                        gallery.init();
                    });

                });
            });


          require(['jquery', '../lib/sweetalert2/dist/sweetalert2.all.min.js'], function ($, Swal) {

                    
                         function bindingFollowEvent() {
                               $('.useraction').unbind("click");
                               $('.useraction').click(function () {
                                var url = "";
                                var isFollow = $(this).hasClass("follow");
                                if (isFollow) {
                                    url = '@Url.Action("Follow","Common")';
                                } else {
                                    url = '@Url.Action("Unfollow","Common")';
                                }
                                var self = this;
                                var followUserId = $(this).data("id");
         
                                $.ajax({
                                    method: 'post',
                                    url: url,
                                    data: { id: followUserId },
                                    dataType: "json",
                                    success: function (data) {
                                
                                        console.log(data);
                                        if (data.success) {
                                            if (isFollow) {
                                                $(self).removeClass("follow")
                                                    .addClass("unfollow");

                                                $(self).html('<span class="fe fe-user-minus  mr-2"></span>Unfollow');
                                          
                                                Swal('', "Followed sucessful", 'success')
                                            }
                                            else {
                                                $(self).removeClass("unfollow")
                                                    .addClass("follow");
                                                $(self).html('<span class="fe fe-user-plus  mr-2"></span>Follow');
                                                Swal('', "Unfollow sucessful", 'success');
                                            }
                               
                                            bindingFollowEvent();
                                        }
                                        else {
                                            Swal('Oops...', data.message, 'error')
                                        }
                                    }, //End of AJAX Success function  

                                    failure: function (data) {
                                        console.log(data);
                                    }, //End of AJAX failure function  
                                    error: function (data) {
                                        console.log(data);
                                    } //End of AJAX error function  
                                });
                            });

                          } 
                    $(document).ready(function () {
                        bindingFollowEvent();
                    });

        });
    </script>
}

GrapePhoto/Views/Home/UserFollowProfile.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

GrapePhoto/Views/Home/UserPhotosThreeColumnsTemplate.cshtml
@using GrapePhoto.Proxy
@inject IAccountClient userManager
@model PostViewModel
@{
    Layout = null;
}
<div class="col-sm-6 col-lg-3">
    <div class="card">
        <a src="@Model.Picture.Src" data-width="@Model.Picture.Width" data-height="@Model.Picture.Height" class="mb-0">
            <img src="@Model.Picture.ThumbnailSrc" class="grapephoto profile-post" alt="@Model.Picture.AltAttribute">
        </a>
        <div class="d-flex align-items-center p-3">
            @if (!string.IsNullOrEmpty(Model.User.AvatarPicUrl))
            {
                <span class="avatar" style="background-image: url('@Model.User.AvatarPicUrl' )">
                </span>
            }
            else
            {
                <span class="avatar avatar-azure mr-3">@Model.User.UserId.Substring(0, 2).ToUpper()</span>
            }
            <div>
                <a href="@Url.Action("Index","Profile", new { id = Model.User.UserId})">@Model.User.UserId</a>
                <small class="d-block text-muted">@Model.Picture.PostDate.ToFriendlyDateTime()</small>
            </div>
            <div class="ml-auto text-muted">
                    @Html.Partial("_LikeComponent", Model)
            </div>
        </div>
    </div>
</div>
 

GrapePhoto/Views/Home/_FollowingPost.cshtml
@model GrapePhoto.Models.PostViewModel
@{
    Layout = null;
}
<div class="card ">
    <a src="@Model.Picture.Src"  data-width="@Model.Picture.Width" data-height="@Model.Picture.Height"><img class="card-img-top grapephoto" src="@Model.Picture.ThumbnailSrc" alt="And this isn&#39;t my nose. This is a false one."></a>
    <div class="card-body d-flex flex-column">
        <h4>@Model.Picture.TitleAttribute</h4>
        <div class="d-flex align-items-center pt-5 mt-auto">

            @if (string.IsNullOrEmpty(Model.User.AvatarPicUrl))
            {
            <div class="avatar avatar-md mr-3">@Model.User.UserId.Substring(0, 2).ToUpper()</div>
            }
            else
            {
                    <div class="avatar avatar-md mr-3" style="background-image: url('@Model.User.AvatarPicUrl')"></div>
            }
            <div>
                <a href="@Url.Action("Index","Profile", new { id = Model.User.UserId})" class="text-default">@Model.User.UserId</a>
                <small class="d-block text-muted">@Model.Picture.PostDate.ToFriendlyDateTime()</small>
            </div>
            <div class="ml-auto text-muted">
                @Html.Partial("_LikeComponent", Model)
            </div>
        </div>
    </div>
</div>

 

GrapePhoto/Views/Home/_FollowingUserItems.cshtml
@model GrapePhoto.Web.Models.Account.User

@{
    Layout = null;
}


<li class="list-separated-item">
    <div class="row align-items-center">
        <div class="col-auto">
            @if (string.IsNullOrEmpty(Model.AvatarPicUrl))
                {
                    <div class="avatar avatar-md mr-3">@Model.UserId.Substring(0, 2).ToUpper()</div>
            }
            else
            {
                    <span class="avatar avatar-md d-block" style="background-image: url('@Model.AvatarPicUrl')"></span>
            }

        </div>
        <div class="col">
            <div>
                <a href="javascript:void(0)" class="text-inherit">@Model.UserId</a>
            </div>
        </div>
        <div class="col-auto">
            <div class="item-action dropdown">
                <a href="javascript:void(0)" data-toggle="dropdown" class="icon"><i class="fe fe-more-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="@Url.Action("Index","Profile", new { id = Model.UserId})" class="unfollowaction dropdown-item" data-id="@Model.UserId"><i class="dropdown-icon fe fe-tag"></i> Unfollow </a>
                </div>
            </div>
        </div>
    </div>
</li>